# Generated by Django 3.0.7 on 2020-11-15 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], default='breakfast', max_length=40)),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=10)),
                ('desc', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_no', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=20)),
                ('passwords', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toal_amount', models.CharField(default=0, max_length=500, null=True)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canteen.Items')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canteen.Users')),
            ],
            options={
                'unique_together': {('user', 'items')},
            },
        ),
        migrations.CreateModel(
            name='Ordered_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', models.CharField(max_length=20)),
                ('payment_status', models.CharField(default='false', max_length=10)),
                ('order_status', models.CharField(default='unserved', max_length=10)),
                ('user_items', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='canteen.UserItem')),
            ],
            options={
                'db_table': 'ordered_item',
            },
        ),
    ]
