# Generated by Django 3.0.7 on 2020-11-15 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(default='false', max_length=10)),
                ('order_status', models.CharField(default='unserved', max_length=10)),
                ('user_items', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='canteen.UserItem')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.DeleteModel(
            name='Ordered_item',
        ),
    ]
